version: "3.9"
services:
  atc_rabbitmq:
    container_name: atc_rabbitmq
    hostname: atc_rabbitmq
    image: rabbitmq:3.8.14-management
    restart: always
    ports:
      - 15674:15672
      - 5674:5672
    env_file:
      - ./pe_reports_django_project/.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - PATH=/opt/rabbitmq/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - RABBITMQ_DATA_DIR=/var/lib/rabbitmq
      - RABBITMQ_VERSION=3.8.14
      - RABBITMQ_HOME=/opt/rabbitmq
      - RABBITMQ_LOGS=-
      - HOME=/var/lib/rabbitmq
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - ./pe_reports_django_project/data/rabbitmq/data:/var/lib/rabbitmq/mnesia:rw
      - ./pe_reports_django_project/config:/etc/rabbitmq:rw
    networks:
      - atc_network

  atc_redis:
    container_name: atc_redis
    hostname: atc_redis
    image: redis:7.4.1
    restart: always
    ports:
      - 6378:6379
    volumes:
      - ./pe_reports_django_project/redis_data:/data
    networks:
      - atc_network

  web:
    build: .
    container_name: atc_web
    volumes:
      - ./pe_reports_django_project:/code
      - ./pe_reports_django_project/config:/code/config
    ports:
      - "8002:8000"
    env_file:
      - pe_reports_django_project/.env
    environment:
      - DJANGO_SETTINGS_MODULE:pe_reports_django.settings
    networks:
      - atc_network
    


  nginx:
    image: nginx:1.25.0
    container_name: atc_nginx
    ports:
      - "8091:8091"
    volumes:
      - ./pe_reports_django_project/config/nginx_config_conf.d:/etc/nginx/conf.d
    networks:
      - atc_network
    depends_on:
      - web

  # database:
  #   image: postgres
  #   restart: always
  #   env_file:
  #     - ./pe_reports_django_project/.env
  #   networks:
  #     - atc_network
  #   volumes:
  #     - ./pe_reports_django_project/postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - 5437:5432
  #   container_name: atc_database

networks:
  atc_network:
    driver: bridge



volumes:
  redis_data: {}