server {
    listen 8091;
    server_name localhost;

    location / {
        proxy_pass http://web:8000; # Assuming 'web' is the service name and '8000' is the port where Gunicorn runs
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}